# Dockerfile

# Paso 1: Usar una imagen oficial de Node.js como base
FROM node:18-alpine

# Paso 2: Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Paso 3: Copiar los archivos de configuración de paquetes
COPY package*.json ./

# Paso 4: Instalar las dependencias
RUN npm install

# Paso 5: Copiar el resto del código de la aplicación
COPY . .

# Paso 6: Construir la aplicación NestJS
RUN npm run build

# Paso 7: Exponer el puerto en el que corre la aplicación
EXPOSE 3000

# Paso 8: El comando para ejecutar la aplicación cuando el contenedor se inicie
CMD ["npm", "run", "start:prod"]